In [13]:
# Lesson 0.2 — NumPy: Everything You Need for AI/ML

## 1. The ndarray — NumPy's Core Object

import numpy as np

# 1D array (a vector)
v = np.array([1, 2, 3, 4, 5])
print(v.shape)   # (5,)
print(v.dtype)   # int64

# 2D array (a matrix)
m = np.array([[1, 2, 3],
              [4, 5, 6]])
print(m.shape)   # (2, 3)  ← 2 rows, 3 columns

# 3D array (batch of matrices — how images are stored)
t = np.zeros((32, 224, 224))   # 32 images, 224x224 pixels
print(t.shape)   # (32, 224, 224)

### **Rule:** Always print `.shape` when debugging. 90% of ML errors are shape mismatches.

## 2. Creating Arrays You'll Use Constantly

v1 = np.zeros((3, 4))             # 3x4 zeros
print(v1)
np.ones((2, 3))              # 2x3 ones
np.eye(4)                    # 4x4 identity matrix (diagonal = 1)
np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
np.linspace(0, 1, 5)         # [0.0, 0.25, 0.5, 0.75, 1.0]
np.random.randn(3, 3)        # random normal (mean=0, std=1) — very common in ML
np.random.rand(3, 3)         # random uniform [0, 1)
np.random.randint(0, 10, (3, 3))  # random integers 0–9
np.full((2, 3), 7)           # 2x3 matrix filled with 7

## 3. Data Types (dtype) — Critical for GPU/Memory

a = np.array([1, 2, 3], dtype=np.float32)   # 32-bit float — PyTorch default
b = np.array([1, 2, 3], dtype=np.float64)   # 64-bit float — NumPy default
c = np.array([1, 2, 3], dtype=np.int32)     # 32-bit int

a.astype(np.float64)   # convert dtype

### Why it matters: GPU memory is expensive. PyTorch uses `float32` by default to fit more data on the GPU.
### NumPy uses `float64` by default. Mismatches cause errors when moving data between NumPy and PyTorch.

## 4. Indexing and Slicing

a = np.array([10, 20, 30, 40, 50])
a[0]       # 10  — first element
a[-1]      # 50  — last element
a[1:3]     # [20, 30]  — slice (end exclusive)
a[::2]     # [10, 30, 50]  — every 2nd element

# 2D
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
m[0, 1]    # 2   — row 0, col 1
m[:, 1]    # [2, 5, 8]   — ALL rows, column 1
m[1, :]    # [4, 5, 6]   — row 1, ALL columns
m[0:2, 1:] # [[2, 3], [5, 6]]  — submatrix

# Boolean indexing — filter rows by condition
scores = np.array([55, 80, 45, 90, 70])
scores[scores > 60]    # [80, 90, 70]
scores[scores > 60] = 100  # set those values to 100 — in-place

## 5. Vectorized Operations — Replace All Your Loops

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

# Element-wise operations
a + b        # [11, 22, 33, 44]
a * b        # [10, 40, 90, 160]
a / b        # [0.1, 0.1, 0.1, 0.1]
a ** 2       # [1, 4, 9, 16]
np.sqrt(a)   # [1.0, 1.41, 1.73, 2.0]
np.exp(a)    # [e^1, e^2, e^3, e^4]
np.log(a)    # natural log

# Matrix multiplication — the core operation in neural networks
A = np.random.randn(3, 4)
B = np.random.randn(4, 5)
C = A @ B          # shape: (3, 5) — matrix multiply
C = np.dot(A, B)   # same thing

### **Neural network forward pass = matrix multiplications.** `A @ B` is what happens millions of times per second during training.


## 6. Aggregations — Along Axes

m = np.array([[1, 2, 3],
              [4, 5, 6]])

m.sum()           # 21  — total
m.sum(axis=0)     # [5, 7, 9]  — sum down rows (one value per COLUMN)
m.sum(axis=1)     # [6, 15]    — sum across columns (one value per ROW)

m.mean(axis=0)    # column means
m.max(axis=1)     # max per row
m.argmax(axis=1)  # INDEX of max per row  — used in classification output
m.std()           # standard deviation
m.var()           # variance

### `axis=0` = collapse rows (vertical), `axis=1` = collapse columns (horizontal).
### Think: "which axis disappears?" `axis=0` removes the row dimension.

## 7. Shape Manipulation — Reshape, Transpose, Squeeze, Stack

a = np.arange(12)          # [0, 1, ..., 11]  shape: (12,)

# Reshape
a.reshape(3, 4)            # (3, 4)
a.reshape(2, 2, 3)         # (2, 2, 3)
a.reshape(-1, 4)           # -1 = "figure it out" → (3, 4)
a.reshape(3, -1)           # → (3, 4)

# Transpose
m = np.array([[1, 2, 3], [4, 5, 6]])  # (2, 3)
m.T                        # (3, 2) — swap rows and columns

# Flatten — make any array 1D
m.flatten()                # [1, 2, 3, 4, 5, 6]
m.ravel()                  # same, but may return a view (no copy)

# Add/remove dimensions
a = np.array([1, 2, 3])    # shape (3,)
a[np.newaxis, :]           # shape (1, 3) — add row dimension
a[:, np.newaxis]           # shape (3, 1) — add column dimension
np.expand_dims(a, axis=0)  # same as newaxis trick
np.squeeze(a)              # remove dimensions of size 1

# Stack arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.stack([x, y])           # [[1,2,3],[4,5,6]]  shape (2, 3)
np.vstack([x, y])          # same — vertical stack
np.hstack([x, y])          # [1,2,3,4,5,6]     — horizontal stack
np.concatenate([x, y])     # [1,2,3,4,5,6]     — general concat

### `reshape` and `newaxis` are used constantly in ML to fix shape errors between layers.

## 8. Broadcasting — NumPy's Most Powerful (and Confusing) Feature

### Broadcasting allows operations between arrays of **different shapes** without copying data.

# Rule: compare shapes from the RIGHT. Dims must match or one must be 1.

a = np.array([[1, 2, 3],
              [4, 5, 6]])    # shape (2, 3)
b = np.array([10, 20, 30])  # shape    (3,)
a + b   # b is broadcast across rows → [[11,22,33],[14,25,36]]

# Adding a column vector
col = np.array([[100],
                [200]])      # shape (2, 1)
a + col  # → [[101,102,103],[204,205,206]]

# Scalar broadcast
a * 2    # every element × 2

## 9. Copies vs Views — A Subtle Bug Source

a = np.array([1, 2, 3, 4])

# View — shares memory with original (NO copy)
b = a[1:3]
b[0] = 99
print(a)   # [1, 99, 3, 4]  ← a was modified!

# Copy — independent
c = a[1:3].copy()
c[0] = 0
print(a)   # unchanged

# Check: does this share memory?
np.shares_memory(a, b)   # True

### Views are fast (no copy), but mutations are shared. Always `.copy()` if you need independence.
### This is the source of many subtle bugs in data preprocessing pipelines.


## 10. Random Number Generation — Reproducibility

# Always set a seed for reproducible experiments
np.random.seed(42)

# Modern way (preferred)
rng = np.random.default_rng(42)
rng.normal(0, 1, (3, 3))      # random normal
rng.integers(0, 10, (3, 3))   # random ints
arr = np.array([1, 2, 3, 4, 5])
rng.shuffle(arr)               # in-place shuffle
print(arr)

### Reproducibility is critical in ML. Two runs with the same seed produce identical results.
### This is how you verify experiments and debug non-deterministic bugs.

## 11. Linear Algebra Operations — What Neural Networks Run On

A = np.random.randn(3, 3)

np.linalg.norm(A)          # Frobenius norm (magnitude of matrix)
np.linalg.det(A)           # determinant
np.linalg.inv(A)           # matrix inverse
np.linalg.eig(A)           # eigenvalues and eigenvectors
np.linalg.svd(A)           # singular value decomposition — used in PCA

# Dot product (also the core of attention mechanism in transformers)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)               # 32  (1×4 + 2×5 + 3×6)

## 12. Useful Utility Functions

# Sorting
a = np.array([3, 1, 4, 1, 5, 9])
np.sort(a)           # [1, 1, 3, 4, 5, 9] — returns new array
np.argsort(a)        # [1, 3, 0, 2, 4, 5] — indices that would sort it

# Unique values
np.unique(a)         # [1, 3, 4, 5, 9]
np.unique(a, return_counts=True)  # with frequencies

# Clipping
np.clip(a, 2, 6)     # [3, 2, 4, 2, 5, 6] — values below 2 → 2, above 6 → 6

# Where (conditional selection)
np.where(a > 3, a, 0)   # keep values > 3, replace others with 0

# Check for NaN/Inf
np.isnan(a.astype(float))
np.isinf(a.astype(float))
np.nan_to_num(a.astype(float), nan=0.0)   # replace NaN with 0

# Percentile
np.percentile(a, 75)    # 75th percentile

## 13. Memory Layout — Why This Affects Performance

# C order (row-major) — default, rows are contiguous in memory
a = np.array([[1, 2, 3], [4, 5, 6]], order='C')

# Fortran order (column-major) — columns contiguous
b = np.array([[1, 2, 3], [4, 5, 6]], order='F')

print(a.flags['C_CONTIGUOUS'])   # True for C-order

# Make contiguous for interop with external libraries
a = np.ascontiguousarray(a)

### You'll hit this when passing NumPy arrays to OpenCV, CUDA, or certain model layers.

## Practice Exercise

import numpy as np
np.random.seed(42)

# Simulate a mini dataset: 100 samples, 5 features
X = np.random.randn(100, 5).astype(np.float32)

# Normalize each feature (subtract mean, divide by std) — z-score
means = X.mean(axis=0)    # shape (5,)
stds  = X.std(axis=0)     # shape (5,)
X_norm = (X - means) / stds   # broadcasting: (100,5) - (5,) → (100,5)

print("Shape:", X_norm.shape)
print("Means after normalization:", X_norm.mean(axis=0).round(4))
print("Stds after normalization:", X_norm.std(axis=0).round(4))

# Find samples where ALL features are > 0
mask = (X_norm > 0).all(axis=1)
print("Samples with all features > 0:", mask.sum())

(5,)
int64
(2, 3)
(32, 224, 224)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[ 1 99  3  4]
[ 1 99  3  4]
[2 1 5 3 4]
True
Shape: (100, 5)
Means after normalization: [-0. -0.  0. -0. -0.]
Stds after normalization: [1. 1. 1. 1. 1.]
Samples with all features > 0: 1
